# Site settings
author: Audrea Cook
title: The Code Witch
header-img: img/home-bg.png
email: audreacwork@gmail.com
copyright_name: Audrea Cook
description: > # this means to ignore newlines until "baseurl:"
  A little magic goes a long way, especially in code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: AudTheCodeWitch
github_username:  AudTheCodeWitch

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
